version: '3.7'

services:
  
  api:
    container_name: api
    build:
      context: .
      target: development
    env_file:
      - .env
    environment:
      - DATABASE_URI=${DATABASE_URI}
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: yarn start

  mongodb:
    container_name: 'mongodb'
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - mongodata:/data/db
    restart: 
      unless-stopped

volumes:
  mongodata: 
    